GET http://localhost:3001

###

GET http://localhost:3001/persons

###

GET http://localhost:3001/persons/65b027bd45a516475054e6af

###

DELETE http://localhost:3001/persons/65b027bd45a516475054e6af

###

POST http://localhost:3001/persons
Content-Type: application/json

{
  "name": "Mariano Molina",
  "number": "261 566 2351"
}

###

POST http://localhost:3001/persons
Content-Type: application/json

{
  "name": "Ada Lovelace",
  "number": "261 304 2443"
}

###

POST http://localhost:3001/persons
Content-Type: application/json

{
  "name": "",
  "number": ""
}