GET http://localhost:3001

###

GET http://localhost:3001/persons

###

GET http://localhost:3001/persons/2

###

DELETE http://localhost:3001/persons/2

###

POST http://localhost:3001/persons
Content-Type: application/json

{
  "name": "Tomas Carrizo",
  "number": "261 304 2443"
}

###

POST http://localhost:3001/persons
Content-Type: application/json

{
  "name": "Ada Lovelace",
  "number": "261 304 2443"
}

###

POST http://localhost:3001/persons
Content-Type: application/json

{
  "name": "",
  "number": ""
}