GET http://localhost:3001

###

GET http://localhost:3001/persons

###

GET http://localhost:3001/info

###

GET http://localhost:3001/persons/65b05b444f6fa1cdeac7deaf

###

DELETE http://localhost:3001/persons/65b05dd17c55d203d2862b9c

###

POST http://localhost:3001/persons
Content-Type: application/json

{
  "name": "er",
  "number": "261 566 2351"
}

###

POST http://localhost:3001/persons
Content-Type: application/json

{
  "name": "Ada Lovelace",
  "number": "261 304 2443"
}

###

POST http://localhost:3001/persons
Content-Type: application/json

{
  "name": "",
  "number": ""
}

###

PUT http://localhost:3001/persons/65b05b444f6fa1cdeac7deaf
Content-Type: application/json

{
  "name": "a",
  "number": "2"
}